# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Set Read the Docs config file spec
version: 2

# Python environment details
python:
  install:
  - requirements: requirements.txt

# Build documentation with Sphinx
sphinx:
  configuration: conf.py

# Additional Build formats aside from HTML
formats:
  - htmlzip
