# GitHub Actions workflow file to automatically build and deploy HTML files to GitHub Pages

name: Update GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build job
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone the repository
        uses: actions/checkout@v2

      # Sets up the running machine
      - name: Install dependencies
        run: | 
          sudo apt-get install python3-sphinx
          pip install sphinx-typlog-theme

      # Uses Sphinx to build the HTML files        
      - name: Build HTML files using Sphinx
        run: make html
  
      # Updates GitHub Pages with the updated build
      - name: Swap branch to gh-pages
        run: git checkout gh-pages

      - name: Delete older build files
        run: rm -r !("_build"|".gitignore") +(".buildinfo"|".nojekyll")

      - name: Move built HTML files to root
        run: |
          mv _build/html/* .
          mv _build/html/.* .

      - name: Commit and push changes
        run: |
          git commit -m "Updated HTML build to $GITHUB_SHA"
          git push origin gh-pages
