# GitHub Actions workflow file to automatically build and deploy HTML files to GitHub Pages

name: Update GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build job
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Checks out the entire repository with all branches and commits
          fetch-depth: 0

      - name: Checkout master and gh-pages
        run: |
          git checkout master
          git checkout gh-pages
          git switch master

      # Sets up the running machine
      - name: Install dependencies
        run: |
          sudo pip install -U Sphinx
          sudo pip install sphinx-typlog-theme

      # Uses Sphinx to build the HTML files
      - name: Swap branch to master
        run: git switch master
      
      - name: Build HTML files using Sphinx
        run: make html
  
      # Updates GitHub Pages with the updated build
      - name: Swap branch to gh-pages
        run: git switch gh-pages

      - name: Delete older build files
        run: |
          shopt -s extglob
          rm -r -- !("_build"|".gitignore"|".nojekyll") +(".buildinfo")

      - name: Move built HTML files to root
        run: |
          cp -r _build/html/* .

      - name: Adds new files (in case there are)
        continue-on-error: true
        run: |
          git add *
      
      - name: Commit changes to gh-pages
          git commit -m "Updated build to ${GITHUB_SHA}"



